-- This file is intentionally left blank.
-- You can add SQL statements here to create missing tables if needed.
-- Example:
-- CREATE TABLE IF NOT EXISTS system_logs (...);

-- Table: system_logs
CREATE TABLE IF NOT EXISTS system_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT DEFAULT NULL,
  user_type ENUM('admin','voter') DEFAULT NULL,
  action VARCHAR(100) NOT NULL,
  description TEXT DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_user_id (user_id),
  KEY idx_user_type (user_type),
  KEY idx_action (action),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create initial admin if not exists
INSERT INTO admins (username, password, fullname, created_at)
SELECT * FROM (SELECT 'admin', '$2y$10$examplehashforadminpassword', 'System Administrator', NOW()) AS tmp
WHERE NOT EXISTS (
    SELECT username FROM admins WHERE username = 'admin'
) LIMIT 1;
--
-- Replace '$2y$10$examplehashforadminpassword' with a real hash generated by PHP's password_hash()
-- Example for password 'admin123':
-- $2y$10$wH8Qw6Qw6Qw6Qw6Qw6Qw6uQw6Qw6Qw6Qw6Qw6Qw6Qw6Qw6Qw6Qw6
